stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

# Stage 1: Install dependencies
install_dependencies:
  stage: install
  image: node:14
  script:
    - npm install

# Stage 2: Run tests
run_tests:
  stage: test
  image: node:14
  script:
    - npm test
  only:
    - develop  

# build_project:
#   stage: build
#   image: node:14
#   script:
#     - npm run build
#   only:
#     - main

# deploy_production:
#   stage: deploy
#   image: node:14
#   script:
#     - echo "Deploying to production server..."
#     - ssh user@yourserver.com 'cd /path/to/your/app && git pull && npm install && pm2 restart app'
#   only:
#     - main